aws_dbt_snowflake_project:
  outputs:
    dev:
      account: FUZDEPL-IO96365
      database: PRAVEEN_DB
      password: Praveeng@19061986
      role: ACCOUNTADMIN
      schema: STAGING
      threads: 1
      type: snowflake
      user: praveengaurav
      warehouse: COMPUTE_WH
  target: dev
